### ISSUE TITLE
[BUG] Doesn't work on Windows

### ISSUE THREAD

**Issue by lukasong** [easonwong-de/White-Sur-Firefox-Theme-MacOS#1]
### Describe the problem

Everything on Firefox becomes click-through and unresponsive, but the repo this is forked from works. Love the extension, so would love to see Windows support!

### Version

219b30cba02a5a35578475f7184e6e0624f238a2

### OS

Windows 11

### Firefox Version

112.0.2

### Install Options

Manual

### Colour Theme

N/A

### Please tick the boxes

- [X] You are using a [current](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/releases/) version of the theme. (check the date associated with the version)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/adamxweb/WhiteSurFirefoxThemeMacOS/issues?q=is%3Aissue)

**Comment by easonwong-de** [comment]
@lukasong Hello! I’m terribly sorry that I respond quite late, which is partly caused by GitHub not sending any notification about the issue to me.

Does the problem still persist with the latest version of everything? If so, I’ll switch to Windows to do some testing.

**Comment by lukasong** [comment]
Seems to work fine on the latest version. Thanks!

**Comment by easonwong-de** [comment]
Glad to hear that.

If the same bug happens again, you are welcomed to reöpen the issue; if any other problem appears, feel free to open a new issue.
