### ISSUE TITLE
I don't have close min and max buttons when using this theme 

### ISSUE THREAD

**Issue by F3R96** [easonwong-de/White-Sur-Firefox-Theme-MacOS#10]
![imagen](https://github.com/easonwong-de/White-Sur-Firefox-Theme-MacOS/assets/78397863/0c945bb1-b848-46fa-a3d9-5b8bef962364)

**Comment by easonwong-de** [comment]
Sorry. I might not be able to test the theme on Linux. If you have found the way to fix this, feel free to make a pull request.

**Comment by F3R96** [comment]
Im using windows 10, and I can't get this theme to show those buttons. I tried adam's whitesur theme and it works, but I wanna use this one

**Comment by easonwong-de** [comment]
Hi, @F3R96, does the issue persist? The Firefox UI has been changed quite a few times since then.
