### ISSUE TITLE
Messed up titlebar

### ISSUE THREAD

**Issue by GioGio-V** [easonwong-de/White-Sur-Firefox-Theme-MacOS#15]
This issue with my titlebar appeared today, the min/close buttons appear next to the new page button and the row of the searchbar is unaligned when searching, tried reinstalling but nothing changed
![image](https://github.com/user-attachments/assets/3b8e889e-34dc-4421-83ec-6d587d5c4f6f)

**Comment by easonwong-de** [comment]
@GioGio-V I updated to Firefox v133, and my title bar is messed up too. Fixes are underway. Thanks for reporting the bug.

**Comment by easonwong-de** [comment]
The issues should be fixed now.
