### ISSUE TITLE
[BUG] URL Bar resizing

### ISSUE THREAD

**Issue by dswapnil104** [easonwong-de/White-Sur-Firefox-Theme-MacOS#18]
Issue: URL Bar tries to resize itself as search query is being typed in.

https://github.com/user-attachments/assets/f0d56537-1c9d-44d9-ae19-aa1cf75af643

**Comment by easonwong-de** [comment]
Hi, @dswapnil104. Could you specify your setup, e.g. Firefox version, OS, etc.?

**Comment by dswapnil104** [comment]
> Hi, @dswapnil104. Could you specify your setup, e.g. Firefox version, OS, etc.?

Sorry about that. 
Firefox 128 (Floorp)
Windows 11 23H2

**Comment by dswapnil104** [comment]
Albeit a lazy fix for the timebeing, but replacing:

> headerbar-private-urlbar.css
> headerbar-urlbar.css

with commit f3d4cb2 release fixes it completely.

**Comment by easonwong-de** [comment]
Glad you found a workaround. But, this CSS theme is only optimised for release version of Firefox. Fixing an issue in one Firefox fork may result in issues in another one.
