### ISSUE TITLE
[BUG] latest firefox broke the theme

### ISSUE THREAD

**Issue by F3R96** [easonwong-de/White-Sur-Firefox-Theme-MacOS#2]
### Describe the problem

buttons got inverted basically 

### Version

latest

### OS

windows 10

### Firefox Version

113.0

### Install Options

none

### Colour Theme

default

### Additional info

![imagen](https://github.com/easonwong-de/WhiteSurFirefoxThemeMacOS/assets/78397863/fd13cc26-bd85-4acc-a5c7-ba1c469b9339)

### Please tick the boxes

- [X] You are using a [current](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/releases/) version of the theme. (check the date associated with the version)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/adamxweb/WhiteSurFirefoxThemeMacOS/issues?q=is%3Aissue)

**Comment by F3R96** [comment]
![imagen](https://github.com/easonwong-de/WhiteSurFirefoxThemeMacOS/assets/78397863/5b66a399-e896-4d0e-a4f3-7cc0e4ba51a0)
And for weeks now, latest releases have been bugging the whole browser in two ways. the one above and this one below:
![imagen](https://github.com/easonwong-de/WhiteSurFirefoxThemeMacOS/assets/78397863/2c20efd2-8e40-4c3d-a341-b921d55f022b)
I can't use the browser on full screen, also the buttons still inverted

**Comment by F3R96** [comment]
> ![imagen](https://user-images.githubusercontent.com/78397863/237706657-5b66a399-e896-4d0e-a4f3-7cc0e4ba51a0.png) And for weeks now, latest releases have been bugging the whole browser in two ways. the one above and this one below: ![imagen](https://user-images.githubusercontent.com/78397863/237707483-2c20efd2-8e40-4c3d-a341-b921d55f022b.png) I can't use the browser on full screen, also the buttons still inverted

This still happens when pasting the whitesur folder inside the chrome folder, only with this custom version for Adaptive Tab Bar Color. The AdamXweb's works just fine

**Comment by easonwong-de** [comment]
@F3R96 Greetings! I apologize sincerely for my delayed response, as I was not notified about the issue by GitHub, which contributed to the delay. Also, I’m sorry for the inconvenience caused by the issue itself.

I would like to inquire if the problem persists in the most recent versions of everything. If it does, I will transition to Windows to conduct some testing.

**Comment by F3R96** [comment]
> @F3R96 Greetings! I apologize sincerely for my delayed response, as I was not notified about the issue by GitHub, which contributed to the delay. Also, I’m sorry for the inconvenience caused by the issue itself.
> 
> I would like to inquire if the problem persists in the most recent versions of everything. If it does, I will transition to Windows to conduct some testing.

Not a problem! I just like making sure that every problem is being communicate in order to ensure a good performance of the theme, and because I really like how this one works.
Currently this is happening to me on Windows 10

**Comment by easonwong-de** [comment]
@F3R96 @lukasong I finally got to debug the CSS theme on Windows 11. With the newest version, all problems should have been lifted now, except there’s a small misalignment in the right click menu.

I’m terribly sorry for the inconvenience!

**Comment by easonwong-de** [comment]
The issue was mainly caused by a small section in [`csd.css`](https://github.com/easonwong-de/White-Sur-Firefox-Theme-MacOS/blob/99ed56099bf0737d724a32791e24f9bf6896cf06/chrome/WhiteSur/parts/csd.css#L5). The AdamXweb’s version works because there’s a syntax error in front of it, which disables the section and thus stops the issue from happening.
