### ISSUE TITLE
[BUG] Differentiate between tabs

### ISSUE THREAD

**Issue by Hye-Dev** [easonwong-de/White-Sur-Firefox-Theme-MacOS#3]
### Describe the problem

Active and inactive tabs have no borders/color difference so it is very difficult to differentiate between tabs

<img width="1798" alt="image" src="https://github.com/easonwong-de/White-Sur-Firefox-Theme-MacOS/assets/55052584/f927a125-d783-4ea1-80c1-dd02cda81fe6">

### Version

2023-07-11

### OS

macOS 14 Beta 1

### Firefox Version

116.0b8

### Install Options

none

### Colour Theme

no

### Please tick the boxes

- [X] You are using a [current](https://github.com/AdamXweb/WhiteSurFirefoxThemeMacOS/releases/) version of the theme. (check the date associated with the version)
- [X] You've checked that this [issue hasn't already been raised](https://github.com/adamxweb/WhiteSurFirefoxThemeMacOS/issues?q=is%3Aissue)

**Comment by easonwong-de** [comment]
@Hye-Dev Hi, I’m glad that you’re trying out this CSS theme. To differentiate the selected tab from the others, you may try adjusting the values for “Tab bar” and “Toolbar” under the “Customization” section in the **Adaptive Tab Bar Color** settings.

<img width="1089" alt="Screenshot 2023-07-26 at 02 14 54" src="https://github.com/easonwong-de/White-Sur-Firefox-Theme-MacOS/assets/16183548/6fa27d36-c945-45b7-966c-899094aac566">

For now, a clean borderless design with clearly distinguishable selected tab is yet to be developed. For the time being, you can also try the “mini-tabbar” design.

**Comment by Hye-Dev** [comment]
Thank you, that definitely helps. Would there be a way to have a border between the tabs as well so the inactive tabs are more distinguishable?

<img width="1729" alt="image" src="https://github.com/easonwong-de/White-Sur-Firefox-Theme-MacOS/assets/55052584/69e364e1-c172-4d65-97a7-85a16d9d368d">

**Comment by jpsingh10** [comment]
Hi,
just piggy piggy backing off of this post.Is it possible to increase the size of the mini-tabbar tabs? Also is there a way to the change the toolbar height?
thank you

**Comment by easonwong-de** [comment]
@Hye-Dev Yes, it’s totally possible. An example would be:

```
﻿﻿.tabbrowser-tab + .tabbrowser-tab {
	border-inline-start: 1px solid var(--macos-toolbar-border-color);
}
```

**Comment by easonwong-de** [comment]
@jpsingh10 To change the height of the mini-tab tabs, you may head to `chrome/WhiteSur/customs/mini-tabbar.css`, and change from line 41 to line 47 to:

```
/* Please replace ”var(--user-defined-value)” with a valid CSS length value, e.g. ”36px” */

.tabbrowser-tab {
	min-height: var(--user-defined-value) !important;
}

tab > stack {
	height: var(--user-defined-value) !important;
}
```

The simplest way to increase the height of the toolbar is to increase the padding. To do that, you may go to `chrome/WhiteSur/parts/headerbar.css` and change line 8 to:

```
/* Please replace ”var(--user-defined-value)” with a valid CSS length value, e.g. ”36px” */

padding: var(--user-defined-value) 16px var(--user-defined-value) 86px !important;
```

**Comment by easonwong-de** [comment]
@jpsingh10 @Hye-Dev I hope the solution works. I’m closing the issue now.
