### ISSUE TITLE
[BUG] White Toolbar?

### ISSUE THREAD

**Issue by tilsgee** [easonwong-de/White-Sur-Firefox-Theme-MacOS#5]
Browser version: 
![gambar](https://github.com/easonwong-de/White-Sur-Firefox-Theme-MacOS/assets/62179071/df206228-bdd3-47ca-8b26-b44525cd3f95)

Bug in question:
![gambar](https://github.com/easonwong-de/White-Sur-Firefox-Theme-MacOS/assets/62179071/34df58a8-1e3a-4279-838f-0e5adaebd1f1)

**Comment by easonwong-de** [comment]
@tilsgee Thank you for reporting this. I’m sorry, but this CSS theme is only optimised for the release version and the developer edition of Firefox, as the Nighty version may update more frequently. Also, this could actually be an Adaptive Tab Bar Colour bug.
