### ISSUE TITLE
[BUG]hide single tab not working

### ISSUE THREAD

**Issue by ivanleopoldo** [easonwong-de/White-Sur-Firefox-Theme-MacOS#6]
Browser Version:
![image](https://github.com/easonwong-de/White-Sur-Firefox-Theme-MacOS/assets/75525118/6637102d-33c1-43c3-8afe-4000d0d1bdac)

Bug:
<img width="1679" alt="Screenshot 2023-10-06 at 08 53 43" src="https://github.com/easonwong-de/White-Sur-Firefox-Theme-MacOS/assets/75525118/20b48329-ecb9-421a-bb86-1410ea94c483">

Seems like an easy fix but I don't know how :<

**Comment by easonwong-de** [comment]
Removing the “new tab” button from tab bar will work :)
