### ISSUE TITLE
lat bar icon looking off on latest release

### ISSUE THREAD

**Issue by F3R96** [easonwong-de/White-Sur-Firefox-Theme-MacOS#8]
How it looks
![imagen](https://github.com/easonwong-de/White-Sur-Firefox-Theme-MacOS/assets/78397863/f3502a16-b270-4a66-b88d-71416934e3e1)
How it should looked 
![imagen](https://github.com/easonwong-de/White-Sur-Firefox-Theme-MacOS/assets/78397863/1e6ac917-0ed2-4b58-b9c3-0563f2db41fd)

**Comment by easonwong-de** [comment]
Thanks for reporting this.

**Comment by F3R96** [comment]
Hello friend! How can I fix this? 
![imagen](https://github.com/easonwong-de/White-Sur-Firefox-Theme-MacOS/assets/78397863/4bc7d238-ada0-46c4-b2ae-14b5d3c61c50)
Had to use that flex space because the side bar icon got too close to the traffic lights

**Comment by easonwong-de** [comment]
Hello. Sorry for the late reply. Are you using Linux? If so, I may not be able to test it out. The theme looks alright on macOS and Windows.

**Comment by F3R96** [comment]
It's on windows 10. the tab bar ends up too close to the green button, this didn't happen before
